### ISSUE TITLE
Unexpectedly stripping styles

### ISSUE THREAD

**Issue by adamalfredsson** [Semigradsky/postcss-nested-media-queries#2]
Given this input:

```css
@media (min-width: 768px) {
  .row:not(.no-gutters) > .md_col-5,
  .row:not(.no-gutters) > .md_col-10 {
    padding-left: 0.5rem;
    padding-right: 0.5rem;
  }
  .md_col-5 {
    width: 33.3333333%;
  }
  .md_col-10 {
    width: 66.6666667%;
  }
  .md_space-y-0 > :not(template) ~ :not(template) {
    margin-top: 0;
  }
  .md_space-x-1 > :not(template) ~ :not(template) {
    margin-left: 0.25rem;
  }
  .md_space-x-8 > :not(template) ~ :not(template) {
    margin-left: 2rem;
  }
  .md_bg-transparent {
    background-color: transparent;
  }
  .md_bg-opacity-0 {
    --bg-opacity: 0;
  }
  .md_block {
    display: block;
  }
  .md_hidden {
    display: none;
  }
  @media (-ms-high-contrast: none), screen and (-ms-high-contrast: active) {
    .md_ie_block {
      display: block;
    }
  }
  .md_flex-row {
    flex-direction: row;
  }
  .md_flex-col {
    flex-direction: column;
  }
  .md_flex-no-wrap {
    flex-wrap: nowrap;
  }
  .md_items-start {
    align-items: flex-start;
  }
  .md_items-end {
    align-items: flex-end;
  }
  .md_justify-start {
    justify-content: flex-start;
  }
  .md_w-48 {
    width: 12rem;
  }
  .md_w-56 {
    width: 14rem;
  }
  .md_w-1_2 {
    width: 50%;
  }
  .md_w-1_3 {
    width: 33.333333%;
  }
  .md_w-1_4 {
    width: 25%;
  }
  .md_w-full {
    width: 100%;
  }
  .md_w-5_15 {
    width: 33.3333333%;
  }
  .md_z-20 {
    z-index: 20;
  }
}
```

This plugin outputs:

```css
@media (min-width: 768px) {
  .row:not(.no-gutters) > .md_col-5,
  .row:not(.no-gutters) > .md_col-10 {
    padding-left: 0.5rem;
    padding-right: 0.5rem;
  }
  .md_col-5 {
    width: 33.3333333%;
  }
  .md_col-10 {
    width: 66.6666667%;
  }
  .md_space-y-0 > :not(template) ~ :not(template) {
    margin-top: 0;
  }
  .md_space-x-1 > :not(template) ~ :not(template) {
    margin-left: 0.25rem;
  }
  .md_space-x-8 > :not(template) ~ :not(template) {
    margin-left: 2rem;
  }
  .md_bg-transparent {
    background-color: transparent;
  }
  .md_bg-opacity-0 {
    --bg-opacity: 0;
  }
  .md_block {
    display: block;
  }
  .md_hidden {
    display: none;
  }
  .md_flex-col {
    flex-direction: column;
  }
  .md_items-start {
    align-items: flex-start;
  }
  .md_justify-start {
    justify-content: flex-start;
  }
  .md_w-56 {
    width: 14rem;
  }
  .md_w-1_3 {
    width: 33.333333%;
  }
  .md_w-full {
    width: 100%;
  }
  .md_z-20 {
    z-index: 20;
  }
}
@media (min-width: 768px) and (-ms-high-contrast: none),
  screen and (-ms-high-contrast: active) {
  .md_ie_block {
    display: block;
  }
}

```

Some classes are missing, like `.md_w-1_2`.
